-- Storage Policies for course-materials bucket (SCORM uploads)
-- 
-- IMPORTANT: Storage policies cannot be created via SQL directly.
-- You must use the Supabase Dashboard to create these policies.
-- Go to: Storage > Policies > New Policy
--
-- However, if you have admin access and want to try via SQL editor, 
-- you can use these commands (but they may not work due to Supabase restrictions)

-- Policy 1: Service role full access (CRITICAL for SCORM uploads)
-- This allows the service role (used by API routes) to upload/manage files
-- Policy name: "Service role can manage all course-materials"
-- Policy type: ALL (or create separate INSERT, SELECT, UPDATE, DELETE)
-- Policy definition:
-- USING: bucket_id = 'course-materials' AND auth.role() = 'service_role'
-- WITH CHECK: bucket_id = 'course-materials' AND auth.role() = 'service_role'

-- Policy 2: Authenticated users can upload files
-- Policy name: "Authenticated users can upload files"
-- Policy type: INSERT
-- Policy definition:
-- bucket_id = 'course-materials' AND auth.role() = 'authenticated'

-- Policy 3: Authenticated users can view files
-- Policy name: "Authenticated users can view files"
-- Policy type: SELECT
-- Policy definition:
-- bucket_id = 'course-materials' AND auth.role() = 'authenticated'

-- Policy 4: Authenticated users can update files
-- Policy name: "Authenticated users can update files"
-- Policy type: UPDATE
-- Policy definition:
-- bucket_id = 'course-materials' AND auth.role() = 'authenticated'

-- Policy 5: Authenticated users can delete files
-- Policy name: "Authenticated users can delete files"
-- Policy type: DELETE
-- Policy definition:
-- bucket_id = 'course-materials' AND auth.role() = 'authenticated'

-- ============================================
-- RECOMMENDED: Use Supabase Dashboard Instead
-- ============================================
--
-- Step 1: Go to Supabase Dashboard > Storage > Policies
-- Step 2: Select the 'course-materials' bucket
-- Step 3: Click "New Policy"
--
-- Create Policy 1 (CRITICAL for SCORM):
--   Name: "Service role can manage all course-materials"
--   Allowed operation: ALL (or check INSERT, SELECT, UPDATE, DELETE)
--   USING expression: bucket_id = 'course-materials' AND auth.role() = 'service_role'
--   WITH CHECK expression: bucket_id = 'course-materials' AND auth.role() = 'service_role'
--
-- Create Policy 2:
--   Name: "Authenticated users can upload files"
--   Allowed operation: INSERT
--   USING expression: bucket_id = 'course-materials' AND auth.role() = 'authenticated'
--
-- Create Policy 3:
--   Name: "Authenticated users can view files"
--   Allowed operation: SELECT
--   USING expression: bucket_id = 'course-materials' AND auth.role() = 'authenticated'
--
-- Create Policy 4:
--   Name: "Authenticated users can update files"
--   Allowed operation: UPDATE
--   USING expression: bucket_id = 'course-materials' AND auth.role() = 'authenticated'
--
-- Create Policy 5:
--   Name: "Authenticated users can delete files"
--   Allowed operation: DELETE
--   USING expression: bucket_id = 'course-materials' AND auth.role() = 'authenticated'
--
-- ============================================
-- Alternative: Make Bucket Public (Easier but Less Secure)
-- ============================================
--
-- For development/testing, you can make the bucket public:
-- 1. Go to Storage > Buckets
-- 2. Click on 'course-materials' bucket
-- 3. Toggle "Public bucket" to ON
--
-- This bypasses all policies but allows anyone to read/write files.
-- NOT recommended for production!

